logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
#    host: 192.168.179.128 # rabbitMQ的ip地址
#    port: 5672 # 端口
    username: itcast
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2
          max-attempts: 5
          stateless: true
    addresses: 192.168.179.128:8071, 192.168.179.128:8072, 192.168.179.128:8073 # 连接MQ集群